[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
